sudo: false
services:
  - docker
script:
  - docker build --force-rm --no-cache --pull -t quay.io/experimentalplatform/ubuntu:$TRAVIS_BRANCH .
deploy:
  - provider: script
    script: docker login -u "$QUAY_USER" -p "$QUAY_PASS" quay.io && docker push "quay.io/experimentalplatform/ubuntu:$TRAVIS_BRANCH"
    on:
      branch: ci
